server:
  port: 8761

log:
  level: INFO

eureka:
  server:
    enable-self-preservation: false
  client:
    # Dont register itself with eureka
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka